# Generated by Django 3.2.6 on 2022-01-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('lecture', '0006_auto_20220114_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecture.lecture')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
