# Generated by Django 3.2.6 on 2022-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlecture', '0002_alter_customlecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlecture',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customlecture',
            name='time',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
