# Generated by Django 3.2.6 on 2022-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlecture', '0003_auto_20220118_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlecture',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customlecture',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
