# Generated by Django 3.2.6 on 2022-01-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customlecture', '0004_auto_20220125_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlecture',
            name='title',
        ),
    ]
