# Generated by Django 3.2.6 on 2022-01-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'default'), (1, 'career'), (2, 'promotion'), (3, 'organization'), (4, 'department'), (5, 'general')], default=5)),
                ('description', models.CharField(default='', max_length=100)),
                ('allow_anonymous', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
