# Generated by Django 3.2.6 on 2021-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('DEF', 'default'), ('CAR', 'career'), ('PRO', 'promotion'), ('ORG', 'organization'), ('DEP', 'department'), ('GEN', 'general')], default='general'),
        ),
    ]
