# Generated by Django 3.2.6 on 2021-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('DEF', 'default'), ('CAR', 'career'), ('PRO', 'promotion'), ('ORG', 'organization'), ('DEP', 'department'), ('GEN', 'general')], max_length=5),
        ),
    ]
