# Generated by Django 3.2.6 on 2021-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(default='GEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[(0, 'default'), (1, 'career'), (2, 'promotion'), (3, 'organization'), (4, 'department'), (5, 'general')], default=5, max_length=5),
        ),
    ]
