# Generated by Django 3.2.6 on 2021-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
