# Generated by Django 3.2.6 on 2022-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
