# Generated by Django 3.2.6 on 2022-01-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_usercomment_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='comment.comment'),
        ),
    ]
