# Generated by Django 3.2.6 on 2022-01-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('test_number', models.IntegerField()),
                ('test_method', models.IntegerField()),
                ('strategy', models.CharField(max_length=1000)),
                ('problems', models.CharField(max_length=1000)),
                ('subject_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.subjectprofessor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
