# Generated by Django 3.2.6 on 2022-01-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0006_auto_20220114_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('test_method', models.IntegerField()),
                ('strategy', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
