# Generated by Django 3.2.6 on 2022-01-28 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('test_type', models.IntegerField()),
                ('test_method', models.CharField(max_length=150)),
                ('strategy', models.CharField(max_length=1000)),
                ('problems', models.CharField(max_length=1000)),
                ('subject_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.subjectprofessor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
