# Generated by Django 3.2.6 on 2022-01-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_information_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='comment',
            new_name='problems',
        ),
    ]
