# Generated by Django 3.2.6 on 2021-12-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
