# Generated by Django 3.2.6 on 2022-01-05 06:32

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211227_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=user.utils.upload_image),
        ),
    ]
