# Generated by Django 3.2.6 on 2022-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='board_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='board_name',
            field=models.CharField(default='자유게시판', max_length=100),
            preserve_default=False,
        ),
    ]
