# Generated by Django 3.2.6 on 2022-01-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220127_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
