# Generated by Django 3.2.6 on 2022-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_usernotification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_unread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
