# Generated by Django 3.2.6 on 2021-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
