# Generated by Django 3.2.6 on 2021-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
