# Generated by Django 3.2.6 on 2022-01-23 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.PositiveIntegerField(default=0)),
                ('user1_active', models.BooleanField(default=True)),
                ('user2_active', models.BooleanField(default=True)),
                ('user1_unread', models.PositiveIntegerField(default=0)),
                ('user2_unread', models.PositiveIntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_room_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_room_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_announce', models.BooleanField(default=True)),
                ('sender_active', models.BooleanField(default=True)),
                ('receiver_active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=128)),
                ('message_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='message.messageroom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
