# Generated by Django 3.2.6 on 2022-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220126_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_announce',
            field=models.BooleanField(default=False),
        ),
    ]
