# Generated by Django 3.2.6 on 2022-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_is_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
