# Generated by Django 3.2.6 on 2022-01-27 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0005_auto_20220125_0130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('homework', models.IntegerField()),
                ('team_activity', models.IntegerField()),
                ('grading', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('test_count', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('subject_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.subjectprofessor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
