# Generated by Django 3.2.6 on 2022-01-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0006_auto_20220114_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('test_method', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=1000)),
                ('problems', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('homework', models.IntegerField()),
                ('team_activity', models.IntegerField()),
                ('grading', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('test_count', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
