# Generated by Django 3.2.6 on 2022-01-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
