# Generated by Django 3.2.6 on 2021-12-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
