# Generated by Django 3.2.6 on 2021-12-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_userarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='liked',
            new_name='like',
        ),
    ]
