# Generated by Django 3.2.6 on 2021-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_liked_userarticle_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='scrap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
