# Generated by Django 3.2.6 on 2021-12-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scrap_count',
        ),
    ]
