# Generated by Django 3.2.6 on 2022-01-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_userboard'),
        ('article', '0007_imagearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='board.board'),
        ),
    ]
