# Generated by Django 3.2.6 on 2022-01-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_imagearticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='article.article'),
        ),
    ]
