# Generated by Django 3.2.6 on 2022-01-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_imagearticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
