# Generated by Django 3.2.6 on 2022-01-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_userarticle_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='article.article'),
        ),
    ]
