# Generated by Django 3.2.6 on 2022-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_userarticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='nickname_code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
