# Generated by Django 3.2.6 on 2022-01-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_auto_20220119_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('professor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('method', models.CharField(blank=True, default='', max_length=50)),
                ('quota', models.IntegerField(default=0)),
                ('grade', models.IntegerField()),
                ('level', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('category', models.IntegerField()),
                ('number', models.IntegerField()),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('language', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_lecture', to='department.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_lecture', to='department.department')),
                ('subject_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_lecture', to='lecture.subjectprofessor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
