# Generated by Django 3.2.6 on 2022-01-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('level', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('category', models.IntegerField()),
                ('number', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('subject_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='lecture.subjectprofessor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
