# Generated by Django 3.2.6 on 2022-01-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='collage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
