# Generated by Django 3.2.6 on 2022-01-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20220119_2130'),
        ('lecture', '0002_alter_lecture_subject_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_lecture', to='department.college'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_lecture', to='department.department'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_lecture', to='lecture.subjectprofessor'),
        ),
    ]
