# Generated by Django 3.2.6 on 2022-01-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20220114_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='collage',
            new_name='college',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
