# Generated by Django 3.2.6 on 2022-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20220120_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='season',
            field=models.IntegerField(),
        ),
    ]
